# LISTA 10 -  LIBRERÍA NUMPY

## <ins>Ejercicios Obligatorios </ins>

In [2]:
import numpy as np
from numpy import random

## EJERCICIO 1

Crea un array unidimensional de 9 elementos y transfórmalo en un array 3D. Muestra la dimensión y la shape antes y después del reshape.

In [ ]:
# Creamos un array unidimensional que contiene los números del 0 al 8.
d1 = np.arange(9)

# Cambiamos la forma del array d1 a un array 3D con dimensiones 3x3x1.
# Esto significa que tendrá 3 "capas", cada una con 3 filas y 1 columna.
d3 = d1.reshape(3, 3, 1)

# Imprimimos el array d3 para ver su nueva forma.
print(d3)

# Obtenemos el número de dimensiones del array d3.
# La propiedad ndim devuelve el número de dimensiones del array.
d3.ndim

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]


3

## EJERCICIO 2

Dados los arrays 2D ```[[-6, 5], [-4, 3], [-2, 1]] y [[1, 2], [3, 4], [5, 6]]```, concaténalos de modo que obtengas el array ```[[1, 2, -6, -5], [3, 4, -4, -3], [5, 6, -2, -1]]```

In [ ]:
# Creamos el primer array 2D con valores negativos y positivos.
d1 = np.array([[-6, 5], [-4, 3], [-2, -1]])

# Creamos el segundo array 2D con valores positivos.
d2 = np.array([[1, 2], [3, 4], [5, 6]])

# Concatenamos d2 y d1 a lo largo del eje 1 (columnas).
# Esto significa que estamos agregando las columnas de d1 a las de d2.
d_fin = np.concatenate((d2, d1), axis=1)

# Imprimimos el resultado final de la concatenación.
print(d_fin)

[[ 1  2 -6  5]
 [ 3  4 -4  3]
 [ 5  6 -2 -1]]


## EJERCICIO 3

Dado el array 2D ```[["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]]```, busca las palabras que sean palíndromos. Necesitarás una función universal.

In [ ]:
# Definimos una función que verifica si una palabra es un palíndromo.
def palin(palabra):
    # Comparamos la palabra original con su reverso. Si son iguales, es un palíndromo.
    return palabra == palabra[::-1]

# Usamos np.frompyfunc para aplicar la función 'palin' a un array de numpy.
# Esta función permite que 'palin' se aplique a cada elemento del array.
my_palin = np.frompyfunc(palin, 1, 1)

# Creamos un array 2D que contiene varias palabras para evaluar.
d2 = np.array([["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]])

# Iteramos a través de cada fila del array 2D.
for fila in d2:
    # Iteramos a través de cada palabra en la fila actual.
    for palabra in fila:
        # Llamamos a 'my_palin' para verificar si la palabra es un palíndromo.
        if my_palin(palabra):
            # Si es un palíndromo, imprimimos un mensaje indicando que la palabra es un palíndromo.
            print(f"La palabra {palabra} es un palíndromo")

La palabra ala es un palindromo
La palabra kayak es un palindromo
La palabra elle es un palindromo


## EJERCICIO 4

Crea un minijuego que piense un número aleatorio entre 1 y 10 y, hasta que no lo aciertes, te pida un número del 1 al 10. Cuando aciertes, tendrá que devolver el número de intentos y la frase: “¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {}”. En caso de que falles, el juego deberá mostrar la frase “¡Has fallado! ¡Prueba otra vez!”

In [ ]:
# Generamos un número aleatorio entre 1 y 10.
num_alt = random.randint(1, 10)

# Inicializamos el contador de intentos en 0.
intentos = 0

# Pedimos al usuario que adivine el número y lo convertimos a un entero.
numero = int(input("Adivina el número aleatorio entre el 1 y el 10: "))

# Iniciamos un bucle que se repetirá mientras el número adivinado sea diferente al número aleatorio.
while numero != num_alt:
    # Incrementamos el contador de intentos por cada intento fallido.
    intentos += 1
    # Informamos al usuario que su intento fue incorrecto.
    print("¡Has fallado! ¡Prueba otra vez!")
    # Pedimos al usuario que adivine nuevamente el número.
    numero = int(input("Adivina el número aleatorio entre el 1 y el 10: "))

# Una vez que el usuario adivina correctamente, incrementamos el contador de intentos por el último intento exitoso.
intentos += 1

# Mostramos un mensaje de felicitación al usuario indicando el número adivinado y el total de intentos realizados.
print("¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {}. Lo has acertado al {} intento".format(num_alt, intentos))

Adivina el numero aleatorio entre el 1 y el 10: 1
¡Has fallado! ¡Prueba otra vez!
Adivina el numero aleatorio entre el 1 y el 10: 2
¡Has fallado! ¡Prueba otra vez!
Adivina el numero aleatorio entre el 1 y el 10: 3
¡Has fallado! ¡Prueba otra vez!
Adivina el numero aleatorio entre el 1 y el 10: 4
¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el 4. Lo has acertado al 4 intento


In [ ]:
# Generamos un número aleatorio entre 1 y 10.
num_alt = random.randint(1, 10)

# Inicializamos el contador de intentos en 0.
intentos = 0

# Iniciamos un bucle infinito que se repetirá hasta que el usuario adivine el número.
while True:
    # Pedimos al usuario que adivine el número y lo convertimos a un entero.
    numero = int(input("Adivina el número aleatorio entre el 1 y el 10: "))

    # Comparamos el número introducido por el usuario con el número aleatorio generado.
    if numero == num_alt:
        intentos += 1  # Incrementamos el contador de intentos.
        # Si el usuario adivina correctamente, mostramos un mensaje de felicitación.
        print("¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {}. Lo has acertado al {} intento".format(num_alt, intentos))
        break  # Salimos del bucle porque se ha acertado el número.
    else:
        intentos += 1  # Incrementamos el contador de intentos por un intento fallido.
        # Informamos al usuario que su intento fue incorrecto y le pedimos que lo intente de nuevo.
        print("¡Has fallado! ¡Prueba otra vez!")

Adivina el numero aleatorio entre el 1 y el 10: 9
¡Has fallado! ¡Prueba otra vez!
Adivina el numero aleatorio entre el 1 y el 10: 2
¡Has fallado! ¡Prueba otra vez!
Adivina el numero aleatorio entre el 1 y el 10: 3
¡Has fallado! ¡Prueba otra vez!
Adivina el numero aleatorio entre el 1 y el 10: 4
¡Has fallado! ¡Prueba otra vez!
Adivina el numero aleatorio entre el 1 y el 10: 5
¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el 5. Lo has acertado al 5 intento


## EJERCICIO 5

Crea un minijuego que piense un array 1D aleatorio de 5 elementos. Los elementos serán números enteros entre 1 y 20. Para cada intento, primero tendrá que pedir 5 números enteros del 1 al 20. El juego nos tendrá que decir cuántos números del array hemos acertado y cuántos números del array están bien colocados. El juego no termina hasta que no se hayan acertado todos los números pensados en la posición correspondiente. Al acabar, se tendrá que mostrar la frase: “¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: {}”

In [ ]:
# Generamos un arreglo de 5 números enteros aleatorios entre 1 y 20.
acertado = random.randint(1, 20, size=5)

# Solicitamos al usuario que ingrese 5 números separados por comas.
numeros = input("Escribe 5 números separados por comas que estén entre 1 y 20: ")

# Convertimos la entrada del usuario en un array de enteros.
num_array = np.array(numeros.split(",")).astype(int)

# Comprobamos si la entrada del usuario es válida (5 números en total, todos entre 1 y 20).
while len(num_array) != 5 or np.any((num_array < 1) | (num_array > 20)):
    # Si no es válida, pedimos al usuario que lo intente de nuevo.
    numeros = input("No has introducido 5 números o no están dentro del rango, vuelve a intentarlo: ")
    num_array = np.array(numeros.split(",")).astype(int)

# Bucle principal que se repite hasta que el usuario adivine el arreglo acertado.
while not np.array_equal(num_array, acertado):
    cont_num = 0  # Contador de números acertados
    cont_pos = 0  # Contador de posiciones acertadas

    # Comprobamos cada número introducido por el usuario.
    for i in range(len(num_array)):
        # Si el número está en el arreglo acertado, incrementamos el contador de números acertados.
        if num_array[i] in acertado:
            cont_num += 1
        # Si el número está en la misma posición, incrementamos el contador de posiciones acertadas.
        if num_array[i] == acertado[i]:
            cont_pos += 1

    # Imprimimos el array introducido por el usuario y los resultados de la comparación.
    print(f"El array que has escrito es: {num_array}")
    print("Has acertado {} números y {} posiciones".format(cont_num, cont_pos))

    # Solicitamos al usuario que ingrese nuevamente 5 números.
    numeros = input("Escribe 5 números separados por comas que estén entre 1 y 20: ")
    num_array = np.array(numeros.split(",")).astype(int)

    # Repetimos la validación de la entrada del usuario.
    while len(num_array) != 5 or np.any((num_array < 1) | (num_array > 20)):
        numeros = input("No has introducido 5 números o no están dentro del rango, vuelve a intentarlo: ")
        num_array = np.array(numeros.split(",")).astype(int)

# Cuando el usuario acierta, mostramos un mensaje de felicitación.
print(f"¡¡ENHORABUENA!!! Has acertado el array que había pensado: {acertado}")

Escribe 5 numero separados por comas que esten entre 1 y 20: 4,10,20,4,5
El array que has escrito es: [ 4 10 20  4  5]
Has acertado 2 numeros y 1 posiciones
Escribe 5 numero separados por comas que esten entre 1 y 20: 4,10,20,9,5
El array que has escrito es: [ 4 10 20  9  5]
Has acertado 1 numeros y 1 posiciones
Escribe 5 numero separados por comas que esten entre 1 y 20: 4,11,15,12,8
El array que has escrito es: [ 4 11 15 12  8]
Has acertado 2 numeros y 1 posiciones
Escribe 5 numero separados por comas que esten entre 1 y 20: 4,11,9,15,8
El array que has escrito es: [ 4 11  9 15  8]
Has acertado 2 numeros y 1 posiciones
Escribe 5 numero separados por comas que esten entre 1 y 20: 4,11,9,9,9
El array que has escrito es: [ 4 11  9  9  9]
Has acertado 1 numeros y 1 posiciones
Escribe 5 numero separados por comas que esten entre 1 y 20: 4,8,9,9,9
El array que has escrito es: [4 8 9 9 9]
Has acertado 2 numeros y 2 posiciones
Escribe 5 numero separados por comas que esten entre 1 y 20: 4,8,

In [ ]:
#ESTE ES EL ANTIGUO, NO PUNTUAR
d1_alt=random.randint(1,20, size = 5)
while True:
  num_array=[]
  numero1=int(input("Escribe el primer numero del 1 al 20: "))
  while True:
    if numero1>0 and numero1<21:
      num_array.append(numero1)
      break
    else:
      numero1=int(input("El numero que has introducido no esta entre el 1 y 20, escribe un numero dentro del rango: "))

  numero2=int(input("Escribe el segundo numero del 1 al 20: "))
  while True:
    if numero2>0 and numero2<21:
      num_array.append(numero2)
      break
    else:
      numero2=int(input("El numero que has introducido no esta entre el 1 y 20, escribe un numero dentro del rango: "))

  numero3=int(input("Escribe el tercer numero del 1 al 20: "))
  while True:
    if numero3>0 and numero3<21:
      num_array.append(numero3)
      break
    else:
      numero3=int(input("El numero que has introducido no esta entre el 1 y 20, escribe un numero dentro del rango: "))

  numero4=int(input("Escribe el cuarto numero del 1 al 20: "))
  while True:
    if numero4>0 and numero4<21:
      num_array.append(numero4)
      break
    else:
      numero4=int(input("El numero que has introducido no esta entre el 1 y 20, escribe un numero dentro del rango: "))

  numero5=int(input("Escribe el quinto numero del 1 al 20: "))
  while True:
    if numero5>0 and numero5<21:
      num_array.append(numero5)
      break
    else:
      numero5=int(input("El numero que has introducido no esta entre el 1 y 20, escribe un numero dentro del rango: "))

  #print(num_array)
  #print(d1_alt)
  cont_num=0
  cont_pos=0
  for x in d1_alt:
    if numero1 == x:
      cont_num+=1
    elif numero2 == x:
      cont_num+=1
    elif numero3 == x:
      cont_num+=1
    elif numero4 == x:
      cont_num+=1
    elif numero5 == x:
      cont_num+=1

  for y in range(len(d1_alt)):
    if num_array[y] == d1_alt[y]:
      cont_pos+=1
  if (num_array == d1_alt).all():
    print(f"¡¡ENHORABUENA!!! Has acertado el array que había pensado: {d1_alt}")
    break
  else:
    print(f"El array que has escrito es: {num_array}")
    print("Has acertado {} numeros y {} posiciones".format(cont_num,cont_pos))


NameError: name 'random' is not defined

## EJERCICIO 6

A partir de la lista ```[-3, -2, -1, 0, 1, 2, 3]```, genera dos arrays aleatorios 2D de size = (3, 4) y súmalos.

In [ ]:
# Creamos un arreglo unidimensional que va de -3 a 3 (excluyendo 4).
lista = np.arange(-3, 4)

# Seleccionamos aleatoriamente valores de 'lista' y creamos una matriz de 3 filas y 4 columnas.
# `random.choice` selecciona elementos de forma aleatoria con reemplazo.
lista1 = random.choices(lista, k=(3, 4))
print(lista1)

# Seleccionamos nuevamente valores aleatorios de 'lista' y creamos otra matriz de 3 filas y 4 columnas.
lista2 = random.choices(lista, k=(3, 4))
print(lista2)

# Sumamos los dos arreglos `lista1` y `lista2` elemento a elemento.
resultado = np.add(lista1, lista2)

# Obtenemos el número de dimensiones del arreglo resultado.
#dimensiones = resultado.ndim

# Imprimimos el resultado de la suma de las dos matrices.
print(resultado)

[[-3  2 -2  0]
 [ 0 -3  3  2]
 [ 2 -3  3  0]]
[[-3  3 -3  3]
 [ 1 -1 -2 -3]
 [-2  1 -1 -2]]
[[-6  5 -5  3]
 [ 1 -4  1 -1]
 [ 0 -2  2 -2]]


## <ins>Ejercicios Opcionales </ins>

## EJERCICIO 7

Dado el array 2D ```[[1, 2, 3],[-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]]``` divídelo en 3 arrays 2D.

In [1]:
# Definimos el array 2D original
array_2d = [[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]]

# Dividir el array en 3 arrays 2D
array_1 = array_2d[:2]  # Primeras dos filas
array_2 = array_2d[2:4]  # Siguientes dos filas
array_3 = array_2d[4:]  # Última fila

# Imprimir los resultados
print("Array 1:", array_1)
print("Array 2:", array_2)
print("Array 3:", array_3)

Array 1: [[1, 2, 3], [-1, 0, 1]]
Array 2: [[4, 5, 6], [-4, 0, 4]]
Array 3: [[3, 2, 1], [-3, 0, 3]]


## EJERCICIO 8

Crea una función universal que dado un array de strings devuelva el número total de vocales de cada string.

In [6]:
# Definimos una lista de palabras
lista = ["colegio", "patio", "ordenador", "python", "programacion"]

# Definimos una función que cuenta el número de vocales en una palabra
def contarvoc(palabra):
    vocales = "aeiou"  # Definimos las vocales que queremos contar
    contador = 0  # Inicializamos un contador en 0 para las vocales
    # Iteramos sobre cada carácter en la palabra
    for char in palabra:
        # Verificamos si el carácter es una vocal (sin distinción de mayúsculas o minúsculas)
        if char.lower() in vocales:
            contador += 1  # Incrementamos el contador si es una vocal
    return contador  # Devolvemos el total de vocales contadas

# Convertimos la función contarvoc a una función universal usando np.frompyfunc
my_contarvoc = np.frompyfunc(contarvoc, 1, 1)

# Aplicamos la función universal al array de palabras
resultado = my_contarvoc(lista)

# Imprimimos el resultado
print(resultado)  # Salida esperada: un array con el número de vocales en cada palabra

[4 3 4 1 5]
